name: synq_manager_example
description: Example app demonstrating synq_manager offline-first sync capabilities

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Local synq_manager package
  synq_manager:
    path: ../
  
  # UI and state management
  cupertino_icons: ^1.0.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true