name: synq_manager_example
description: Example app demonstrating synq_manager offline-first sync capabilities

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Local synq_manager package
  synq_manager:
    path: ../
  
  # Core dependencies
  hive:
    git:
      url: https://github.com/isar/hive.git
      ref: 52384ded658ad573d16137ea643130ad18153c07
  isar_plus_flutter_libs: ^1.0.9
  workmanager: ^0.9.0+3
  
  # UI and state management
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true