include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    avoid_print: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false


