name: synq_manager
description: A powerful synchronization manager for Flutter apps with secure local storage, real-time state management, and background cloud sync capabilities.
version: 1.0.11
homepage: https://github.com/ahmtydn/synq_manager

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_plus_secure: ^1.1.14
  isar_plus_flutter_libs: ^1.0.21
  workmanager: ^0.9.0+3
  meta: ^1.9.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  very_good_analysis: ^5.0.0
