name: synq_manager
description: Offline-first data synchronization engine with intelligent conflict resolution and real-time events.
version: 2.1.8
homepage: https://github.com/ahmtydn/synq_manager
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  rxdart: ^0.27.7
  uuid: ^4.0.0
  crypto: ^3.0.3
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  test: ^1.24.9
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: false
